version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
        keys:
          - v1-deps-{{ checksum "package-lock.json" }}
          - v1-deps-
      - run:
          name: "Deploy to GH Pages"
          command: |
            git config user.name "${CIRCLE_PROJECT_USERNAME}"
            git config user.email "<email>"
            npm install
            npm install --location=global gh-pages --save-dev
            npm run deploy 
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  deployment-workflow:
    jobs:
      - deploy
