version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run:
          name: "Deploy to GH Pages"
          command: |
            git config user.name "${CIRCLE_PROJECT_USERNAME}"
            git config user.email "<email>"
            npm install
            npm install --location=global gh-pages --save-dev
            npm run deploy 

workflows:
  deployment-workflow:
    jobs:
      - deploy
