version: 2.1
jobs:
  dependencies:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - node-deps
  build:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            yarn build
  deploy:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      - run:
          name: "Deploy to GH Pages"
          command: |
            git config user.name "${CIRCLE_PROJECT_USERNAME}"
            git config user.email "<email>"
            yarn add gh-pages --dev
            yarn deploy

commands:
  configure-user:
    description: "install dependencies for node"
    steps:
      - run: |
          git config user.name "${CIRCLE_PROJECT_USERNAME}"
          git config user.email "<email>"

  node-deps:
    description: "install dependencies for node"
    parameters:
      dir:
          description: |
            The directory relative to the root of the repo to run bundle for.
            Leave empty for root directory.
          type: string
          default: ""
    steps:
      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore caches
              - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - yarn-packages-{{ .Branch }}-
              - yarn-packages-
      - run:
          name: Install Node Dependencies
          command: |
            if [[ "<< parameters.dir >>" != "" ]]; then
              cd << parameters.dir >>
            fi
            sudo apt update && sudo apt install yarn
            yarn install
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
            - "<< parameters.dir >>/~/usr/local/lib/node_modules  # location depends on npm version"
            
workflows:
  deployment-workflow:
    jobs:
      - dependencies
      - build
      - deploy:
          filters:
            branches:
              only:
                - main
