version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run:
          name: "Deploy to GH Pages"
          command: |
            npm install
            npm install -g gh-pages --save-dev
            npm run deploy 

workflows:
  deployment-workflow:
    jobs:
      - deploy
