version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:18.3.0
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: "Deploy to GH Pages"
          command: |
            git config user.name "${CIRCLE_PROJECT_USERNAME}"
            git config user.email "<email>"
            npm install
            npm install --location=global gh-pages --save-dev
            npm run deploy 
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

workflows:
  deployment-workflow:
    jobs:
      - deploy
